"use client";

import { useState, useEffect, useRef } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import {
    CheckCircle,
    Sparkle,
    FileText,
    ArrowRight,
    WarningCircle,
    Check,
    Lightning,
    ArrowsClockwise,
    ArrowSquareOut
} from "@phosphor-icons/react";
import { ApplicationDraft } from "../ApplicationWizard";
import { generateTailoringRecommendations } from "@/actions/tailor-resume";
import { TailoringRecommendation, ResumeData } from "@/types/resume";
import { cn } from "@/lib/utils";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { createApplicationDraft } from "@/actions/applications";

interface ResumeTailoringStepProps {
    draft: ApplicationDraft;
    onUpdate: (updates: Partial<ApplicationDraft>) => void;
    resumeData: ResumeData | null;
    resumeLoading: boolean;
    resumeError: string | null;
}

export function ResumeTailoringStep({ draft, onUpdate, resumeData, resumeLoading, resumeError }: ResumeTailoringStepProps) {
    const router = useRouter();
    const [isGenerating, setIsGenerating] = useState(false);
    const [isCreatingDraft, setIsCreatingDraft] = useState(false);
    const [generatingMessage, setGeneratingMessage] = useState("");
    const [error, setError] = useState<string | null>(null);
    const [recommendations, setRecommendations] = useState<TailoringRecommendation[]>(draft.recommendations || []);
    const [selectedIds, setSelectedIds] = useState<Set<string>>(
        new Set(draft.selectedRecommendations?.map((r, i) => r.id || `rec-${i}`) || [])
    );
    const [versionName, setVersionName] = useState(
        draft.versionName || `${draft.jobAnalysis?.companyName || 'Company'} - ${draft.jobAnalysis?.positionTitle || 'Role'}`
    );
    const hasAutoGenerated = useRef(false);

    // Update version name when job analysis loads (if still default)
    useEffect(() => {
        if (draft.jobAnalysis?.companyName && draft.jobAnalysis?.positionTitle) {
            const newName = `${draft.jobAnalysis.companyName} - ${draft.jobAnalysis.positionTitle}`;
            // If current name is generic or empty, update it
            if (!versionName || versionName === "Company - Role" || versionName === "Company - " || versionName.startsWith("Company -")) {
                setVersionName(newName);
                onUpdate({ versionName: newName });
            }
        }
    }, [draft.jobAnalysis?.companyName, draft.jobAnalysis?.positionTitle]);

    // Handle "Tailor in Builder" - saves draft and redirects
    const handleTailorInBuilder = async () => {
        setIsCreatingDraft(true);
        try {
            // Save the draft to get an ID
            const result = await createApplicationDraft(draft);

            if (result.error) {
                throw new Error(result.error);
            }

            if (result.data?.id) {
                // Clear wizard cache since we've "graduated" to a real application
                sessionStorage.removeItem("interview-os:wizard-draft");

                // Redirect to Resume Builder with application context
                router.push(`/resume-builder?applicationId=${result.data.id}&openTailoring=true&source=applications`);
            }
        } catch (e: any) {
            setError(e.message || "Failed to create application");
            setIsCreatingDraft(false);
        }
    };

    // Sync resume data into draft when it arrives from the wizard
    useEffect(() => {
        if (resumeData && !draft.baseResume) {
            onUpdate({ baseResume: resumeData });
        }
    }, [resumeData]);

    // Auto-generate recommendations when resume + job analysis are both ready
    useEffect(() => {
        if (
            resumeData &&
            draft.jobAnalysis &&
            recommendations.length === 0 &&
            !isGenerating &&
            !hasAutoGenerated.current
        ) {
            hasAutoGenerated.current = true;
            handleGenerateRecommendations();
        }
    }, [resumeData, draft.jobAnalysis]);

    // Generate recommendations
    const handleGenerateRecommendations = async () => {
        const resume = resumeData || draft.baseResume;
        if (!resume || !draft.jobAnalysis) return;

        setIsGenerating(true);
        setError(null);
        setGeneratingMessage("Analyzing your resume against job requirements...");

        try {
            const result = await generateTailoringRecommendations(resume, draft.jobAnalysis);

            if (result.error) {
                throw new Error(result.error);
            }

            const recs = result.data || [];
            const recsWithIds = recs.map((r, i) => ({ ...r, id: r.id || `rec-${i}` }));
            setRecommendations(recsWithIds);

            // Select all high priority by default
            const highPriority = recsWithIds
                .filter(r => r.priority === 'high')
                .map(r => r.id!);
            setSelectedIds(new Set(highPriority));

            onUpdate({
                recommendations: recsWithIds,
                selectedRecommendations: recsWithIds.filter(r => highPriority.includes(r.id!)),
                versionName
            });

        } catch (e: unknown) {
            setError((e as Error).message || "Failed to generate recommendations");
        } finally {
            setIsGenerating(false);
            setGeneratingMessage("");
        }
    };

    // Toggle recommendation selection
    const toggleRecommendation = (id: string) => {
        const newSelected = new Set(selectedIds);
        if (newSelected.has(id)) {
            newSelected.delete(id);
        } else {
            newSelected.add(id);
        }
        setSelectedIds(newSelected);

        const selectedRecs = recommendations.filter(r => newSelected.has(r.id!));
        onUpdate({
            selectedRecommendations: selectedRecs,
            versionName
        });
    };

    const selectAll = () => {
        const allIds = new Set(recommendations.map(r => r.id!));
        setSelectedIds(allIds);
        onUpdate({ selectedRecommendations: recommendations, versionName });
    };

    const selectNone = () => {
        setSelectedIds(new Set());
        onUpdate({ selectedRecommendations: [], versionName });
    };

    const handleVersionNameChange = (name: string) => {
        setVersionName(name);
        onUpdate({ versionName: name });
    };

    // Resume still loading (pre-fetched by wizard)
    if (resumeLoading) {
        return (
            <div className="space-y-6">
                <div className="mb-6">
                    <h2 className="text-xl md:text-2xl font-semibold tracking-tight">Tailor Your Resume</h2>
                    <p className="text-sm text-muted-foreground mt-1 leading-relaxed">
                        Loading your resume to generate tailored recommendations...
                    </p>
                </div>
                <div className="bg-card rounded-xl shadow-[var(--shadow-sm)] p-12 text-center">
                    <div className="flex flex-col items-center gap-5">
                        <div className="w-8 h-8 border-2 border-brand/20 border-t-brand rounded-full animate-spin" />
                        <div className="space-y-1">
                            <p className="text-foreground text-sm font-medium">Loading your resume...</p>
                            <p className="text-muted-foreground text-xs">This should only take a moment</p>
                        </div>
                    </div>
                </div>
            </div>
        );
    }

    // Resume fetch had an error
    if (resumeError) {
        const isReimportNeeded = resumeError.includes("re-imported");

        return (
            <div className="space-y-6">
                <div className="mb-6">
                    <h2 className="text-xl md:text-2xl font-semibold tracking-tight">Tailor Your Resume</h2>
                    <p className="text-sm text-muted-foreground mt-1 leading-relaxed">
                        We ran into an issue loading your resume.
                    </p>
                </div>
                <div className="bg-card rounded-xl shadow-[var(--shadow-sm)] border border-dashed border-border">
                    <div className="flex flex-col items-center justify-center p-12 text-center">
                        <div className="w-16 h-16 rounded-2xl bg-destructive/10 flex items-center justify-center mb-4 text-destructive">
                            <WarningCircle size={32} />
                        </div>
                        <h3 className="text-lg font-semibold mb-2">
                            {isReimportNeeded ? "Resume Needs Update" : "Couldn't Load Resume"}
                        </h3>
                        <p className="text-muted-foreground text-sm mb-6 max-w-md leading-relaxed">
                            {isReimportNeeded
                                ? "Your resume data needs to be refreshed. Please re-import it in the Resume Builder, then come back."
                                : resumeError
                            }
                        </p>
                        <div className="flex gap-3">
                            <Link href="/resume-builder?source=applications">
                                <Button className="gap-2" variant="brand">
                                    <FileText size={18} />
                                    Go to Resume Builder
                                    <ArrowSquareOut size={14} />
                                </Button>
                            </Link>
                        </div>
                        <p className="text-xs text-muted-foreground mt-6">
                            You can also skip this step and track the application without resume tailoring.
                        </p>
                    </div>
                </div>
            </div>
        );
    }

    // No resume exists at all
    if (!resumeData) {
        return (
            <div className="space-y-6">
                <div className="mb-6">
                    <h2 className="text-xl md:text-2xl font-semibold tracking-tight">Tailor Your Resume</h2>
                    <p className="text-sm text-muted-foreground mt-1 leading-relaxed">
                        Create a resume first to get AI-powered tailoring recommendations.
                    </p>
                </div>
                <div className="bg-card rounded-xl shadow-[var(--shadow-sm)] border border-dashed border-border">
                    <div className="flex flex-col items-center justify-center p-12 text-center">
                        <div className="w-16 h-16 rounded-2xl bg-brand/10 flex items-center justify-center mb-4 text-brand">
                            <WarningCircle size={32} />
                        </div>
                        <h3 className="text-lg font-semibold mb-2">No Resume Found</h3>
                        <p className="text-muted-foreground text-sm mb-6 max-w-md leading-relaxed">
                            You need to create a resume first before we can tailor it for this job.
                        </p>
                        <Link href="/resume-builder?source=applications">
                            <Button className="gap-2" variant="brand">
                                <FileText size={18} />
                                Go to Resume Builder
                            </Button>
                        </Link>
                        <p className="text-xs text-muted-foreground mt-6">
                            You can also skip this step and track the application without resume tailoring.
                        </p>
                    </div>
                </div>
            </div>
        );
    }

    return (
        <div className="space-y-6">
            <div className="mb-6">
                <h2 className="text-xl md:text-2xl font-semibold tracking-tight">Tailor Your Resume</h2>
                <p className="text-sm text-muted-foreground mt-1 leading-relaxed">
                    Choose how you want to tailor your resume for this application.
                </p>
            </div>

            {/* Main Action: Go to Resume Builder */}
            <div className="bg-gradient-to-br from-brand/5 to-brand/10 rounded-xl border border-brand/20 p-6 md:p-8">
                <div className="flex flex-col md:flex-row items-center gap-6">
                    <div className="w-16 h-16 rounded-2xl bg-brand/20 flex items-center justify-center text-brand shrink-0">
                        <Sparkle size={32} weight="fill" />
                    </div>
                    <div className="flex-1 text-center md:text-left space-y-2">
                        <h3 className="text-lg font-semibold text-foreground">Deep Tailoring in Resume Builder</h3>
                        <p className="text-sm text-muted-foreground leading-relaxed">
                            Use our full-featured editor to create a new version of your resume specifically for this role.
                            We'll save this application and link the new version automatically.
                        </p>
                    </div>
                    <Button
                        onClick={handleTailorInBuilder}
                        disabled={isCreatingDraft}
                        size="lg"
                        className="w-full md:w-auto shrink-0 gap-2 shadow-lg shadow-brand/20"
                        variant="brand"
                    >
                        {isCreatingDraft ? (
                            <>
                                <div className="w-4 h-4 border-2 border-brand-foreground/30 border-t-brand-foreground rounded-full animate-spin mr-2" />
                                Saving...
                            </>
                        ) : (
                            <>
                                <ArrowSquareOut size={18} weight="bold" />
                                Open Builder
                            </>
                        )}
                    </Button>
                </div>
            </div>

            <div className="relative">
                <div className="absolute inset-0 flex items-center">
                    <span className="w-full border-t border-border/60" />
                </div>
                <div className="relative flex justify-center text-xs uppercase">
                    <span className="bg-background px-2 text-muted-foreground font-medium tracking-wider">
                        Or use quick mode
                    </span>
                </div>
            </div>

            <div className="mb-2">
                <p className="text-sm text-muted-foreground">
                    {recommendations.length > 0
                        ? "Review and select the recommendations to apply to your resume."
                        : "Generate AI recommendations right here to optimize your resume."
                    }
                </p>
            </div>

            {/* Version Name Input */}
            <div className="bg-card rounded-xl shadow-[var(--shadow-sm)] p-6">
                <Label htmlFor="versionName">Version Name</Label>
                <Input
                    id="versionName"
                    value={versionName}
                    onChange={(e) => handleVersionNameChange(e.target.value)}
                    placeholder="e.g., Google - Senior Engineer"
                    className="mt-2"
                />
                <p className="text-xs text-muted-foreground mt-2">
                    This will be saved as a new version in your resume history.
                </p>
            </div>

            {/* Generating / Empty / Recommendations */}
            {isGenerating ? (
                <div className="bg-card rounded-xl shadow-[var(--shadow-sm)] p-12 text-center">
                    <div className="flex flex-col items-center gap-5">
                        <div className="w-8 h-8 border-2 border-brand/20 border-t-brand rounded-full animate-spin" />
                        <div className="space-y-1">
                            <p className="text-foreground text-sm font-medium">{generatingMessage}</p>
                            <p className="text-muted-foreground text-xs">This usually takes 10-20 seconds</p>
                        </div>
                    </div>
                </div>
            ) : recommendations.length === 0 ? (
                <div className="bg-card rounded-xl shadow-[var(--shadow-sm)] p-12 text-center">
                    <div className="w-16 h-16 rounded-2xl bg-brand/10 flex items-center justify-center mx-auto mb-4 text-brand">
                        <Sparkle size={32} />
                    </div>
                    <h3 className="text-lg font-semibold mb-2">Generate Recommendations</h3>
                    <p className="text-muted-foreground text-sm mb-6 max-w-md mx-auto leading-relaxed">
                        Our AI will compare your resume with the job requirements and suggest specific improvements to increase your match score.
                    </p>
                    {error && (
                        <div className="mb-4 p-3 bg-destructive/10 border border-destructive/20 rounded-lg text-sm text-destructive">
                            {error}
                        </div>
                    )}
                    <Button
                        onClick={handleGenerateRecommendations}
                        disabled={isGenerating || !resumeData}
                        className="gap-2"
                        size="lg"
                        variant="brand"
                    >
                        <Lightning size={18} weight="fill" />
                        Generate Recommendations
                    </Button>
                </div>
            ) : (
                <div className="space-y-4">
                    {/* Header with actions */}
                    <div className="flex items-center justify-between px-1">
                        <div>
                            <h3 className="font-semibold text-lg">Recommended Changes</h3>
                            <p className="text-sm text-muted-foreground">
                                Select the suggestions you want to apply ({selectedIds.size} selected)
                            </p>
                        </div>
                        <div className="flex gap-2">
                            <Button variant="outline" size="sm" onClick={selectAll}>
                                Select All
                            </Button>
                            <Button variant="outline" size="sm" onClick={selectNone}>
                                Clear
                            </Button>
                            <Button
                                variant="ghost"
                                size="sm"
                                onClick={() => {
                                    hasAutoGenerated.current = false;
                                    setRecommendations([]);
                                    setSelectedIds(new Set());
                                    handleGenerateRecommendations();
                                }}
                                className="gap-1.5"
                            >
                                <ArrowsClockwise size={14} />
                                Regenerate
                            </Button>
                        </div>
                    </div>

                    {/* Recommendations List */}
                    <div className="space-y-3">
                        {recommendations.map((rec) => (
                            <RecommendationCard
                                key={rec.id}
                                recommendation={rec}
                                isSelected={selectedIds.has(rec.id!)}
                                onToggle={() => toggleRecommendation(rec.id!)}
                            />
                        ))}
                    </div>
                </div>
            )}
        </div>
    );
}

// Recommendation Card Component
interface RecommendationCardProps {
    recommendation: TailoringRecommendation;
    isSelected: boolean;
    onToggle: () => void;
}

function RecommendationCard({ recommendation, isSelected, onToggle }: RecommendationCardProps) {
    const categoryIcons: Record<string, string> = {
        summary: "Summary",
        experience: "Experience",
        skills: "Skills",
        competencies: "Competencies"
    };

    return (
        <div
            onClick={onToggle}
            className={cn(
                "bg-card rounded-xl cursor-pointer transition-all duration-200 border-2 overflow-hidden relative group p-5 flex gap-4",
                isSelected
                    ? "border-brand bg-brand/5 shadow-[var(--shadow-md)]"
                    : "border-border/50 hover:border-border hover:shadow-[var(--shadow-sm)]"
            )}
        >
            {/* Checkbox */}
            <div
                className={cn(
                    "w-6 h-6 rounded-full border-2 flex items-center justify-center flex-shrink-0 transition-all mt-1",
                    isSelected
                        ? "bg-brand border-brand"
                        : "border-muted-foreground/30 group-hover:border-brand/50"
                )}
            >
                {isSelected && <Check size={14} weight="bold" className="text-white" />}
            </div>

            {/* Content */}
            <div className="flex-1 min-w-0 space-y-3">
                {/* Header */}
                <div className="flex items-center gap-2">
                    <Badge variant={recommendation.priority === 'high' ? 'destructive' : recommendation.priority === 'medium' ? 'default' : 'secondary'} className="uppercase text-[10px] tracking-wider">
                        {recommendation.priority} Priority
                    </Badge>
                    <span className="text-[10px] text-muted-foreground font-bold uppercase tracking-widest">
                        {categoryIcons[recommendation.category] || recommendation.category}
                    </span>
                </div>

                {/* Before/After */}
                <div className="grid gap-3 p-3 bg-muted/20 rounded-lg border border-border/50">
                    {recommendation.original && (
                        <div className="text-sm">
                            <span className="text-[10px] text-muted-foreground font-bold uppercase tracking-wider block mb-1">Original:</span>
                            <span className="text-muted-foreground line-through opacity-70">
                                {recommendation.original}
                            </span>
                        </div>
                    )}
                    <div className="text-sm">
                        <span className="text-[10px] text-brand font-bold uppercase tracking-wider block mb-1">Suggested:</span>
                        <div className="flex gap-2">
                            <ArrowRight size={16} className="text-brand shrink-0 mt-0.5" />
                            <span className="text-foreground font-medium">
                                {recommendation.suggested}
                            </span>
                        </div>
                    </div>
                </div>

                {/* Reasoning */}
                {recommendation.reasoning && (
                    <div className="flex items-start gap-2 text-xs text-muted-foreground">
                        <Sparkle size={14} className="mt-0.5 shrink-0 text-brand" />
                        <p className="italic">"{recommendation.reasoning}"</p>
                    </div>
                )}
            </div>
        </div>
    );
}
